<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.airxiechao.j20</groupId>
        <artifactId>J20-probe-network</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>biz-probe-network</artifactId>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.airxiechao.j20</groupId>
            <artifactId>api-probe-common</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.airxiechao.j20</groupId>
            <artifactId>api-probe-network</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.airxiechao.j20</groupId>
            <artifactId>biz-probe-common</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.10.2</version>
        </dependency>
        <dependency>
            <groupId>org.pcap4j</groupId>
            <artifactId>pcap4j-packetfactory-static</artifactId>
            <version>1.8.2</version>
        </dependency>
        <dependency>
            <groupId>com.athaydes.rawhttp</groupId>
            <artifactId>rawhttp-core</artifactId>
            <version>2.6.0</version>
        </dependency>
    </dependencies>
</project>